pub const GENERATOR_LENGTH: u16 = 10;
pub const SEQUENCE_LENGTH: u16 = 11;
pub const TIMESTAMP_LENGTH: u64 = 42;

pub const GENERATOR_MASK: u64 = ((1 << GENERATOR_LENGTH) - 1);
pub const SEQUENCE_MASK: u64 = ((1 << SEQUENCE_LENGTH) - 1) << GENERATOR_LENGTH;
pub const TIMESTAMP_MASK: u64 =
    ((1 << TIMESTAMP_LENGTH) - 1) << (GENERATOR_LENGTH + SEQUENCE_LENGTH);
